variable "prefix" {}
variable "cluster_name" {}
variable "retention_days" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "vpc_cidr_block" {}
variable "task_family" {}
variable "task_cpu" {}
variable "task_memory" {}
variable "service_name" {}
variable "ecr_repository_name" {}